### PR TITLE
Implementing ro.py & refactoring

### LINKED ISSUE #7: https://auth.roblox.com/v1/authentication-ticket error
`response = await client.requests.session.post("https://auth.roblox.com/v1/authentication-ticket", headers={"referer": f"https://www.roblox.com/games/{placeId}"})`

I tried to create a POST and apparently not all the necessary parameters are provided as it gives an error. `rbx-authentication-ticket`, this appears to not be a valid header.

### PR DESCRIPTION
**Pull request by ghost**
I have implemented ro.py to correctly verify .ROBLOSECURITY token and place id. I removed some libraries as they were contained in ro.py. I moved the place id definition inside main.py and removed start.bat. I made everything asynchronous. I refactored the code improving the handling of exceptions. **These changes do not resolve #7**.

### CODE REVIEW

**Comment by gapunitec** [comment]
@emppu-dev I tried to fix the problem #7 but couldn't, can you take a look at it by moving to this branch?

**Comment by emppu-dev** [comment]
Will review soon

**Comment by ghost** [comment]
If you can, try to understand why the POST https://auth.roblox.com/v1/authentication-ticket fails and does not return the desired headers. The problem was already present.

**Comment by gapunitec** [comment]
It would be better to put some methods in series rather than in parallel. I take care of it.

**Pull request closed without merging**
